image:
  file: .gitpod.Dockerfile

tasks:
  - command: sudo docker-up &
  - command: jupyter-lab --ip 0.0.0.0 --NotebookApp.token='' --no-browser&
  - command: sudo su

ports:
  - port: 8000-9000
    onOpen: ignore
